app:
  client:
    origins: ${APP_ALLOWED_ORIGINS:https://geocoleta.vercel.app/,http://localhost:3000, https://portal-morador.onrender.com/}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME:7200000} # 2h
  swagger:
    enabled: ${SWAGGER_ENABLED:false}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sendgrid:
    api-key: ${SPRING_SENDGRID_API_KEY}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  config:
    import: optional:file:.env[.properties]

# ============================
# SPRING ACTUATOR (Health Check)
# ============================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
# ============================
# MINIO CONFIGURATION
# ============================
minio:
  url: ${MINIO_URL:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:coleta-incidentes}